// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUJdjtCDkMGVEnLxlSh8-TDtFV5i9yjao',
    appId: '1:584739678671:web:92513233061aab18798aba',
    messagingSenderId: '584739678671',
    projectId: 'diu-transport-f6ef0',
    authDomain: 'diu-transport-f6ef0.firebaseapp.com',
    storageBucket: 'diu-transport-f6ef0.firebasestorage.app',
    measurementId: 'G-Z0MD782NE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRtvUrdS0M4vohACJNcLoSZ8GPp2TPlV8',
    appId: '1:584739678671:android:299bc9dd0ff89f2d798aba',
    messagingSenderId: '584739678671',
    projectId: 'diu-transport-f6ef0',
    storageBucket: 'diu-transport-f6ef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqaVv6dvum85WJVrDR11AedykyXpJRQmY',
    appId: '1:584739678671:ios:697b85d92ef2a748798aba',
    messagingSenderId: '584739678671',
    projectId: 'diu-transport-f6ef0',
    storageBucket: 'diu-transport-f6ef0.firebasestorage.app',
    iosBundleId: 'com.example.diuTransport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqaVv6dvum85WJVrDR11AedykyXpJRQmY',
    appId: '1:584739678671:ios:697b85d92ef2a748798aba',
    messagingSenderId: '584739678671',
    projectId: 'diu-transport-f6ef0',
    storageBucket: 'diu-transport-f6ef0.firebasestorage.app',
    iosBundleId: 'com.example.diuTransport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUJdjtCDkMGVEnLxlSh8-TDtFV5i9yjao',
    appId: '1:584739678671:web:9caffc82bbf40d0a798aba',
    messagingSenderId: '584739678671',
    projectId: 'diu-transport-f6ef0',
    authDomain: 'diu-transport-f6ef0.firebaseapp.com',
    storageBucket: 'diu-transport-f6ef0.firebasestorage.app',
    measurementId: 'G-RN82EJDSQH',
  );
}
